# Generated by Django 5.1.7 on 2025-05-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microEmpresa', '0002_remove_producto_precio_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
